### PR TITLE
Chore/22 remove duplicate code

### PR DESCRIPTION
**Pull request by firesetter**
#22

### CODE REVIEW

**Comment by Alexander-Prime** [comment]
These changes look good, but was this meant to be merged onto [release/v0.1.0](/AlwaysBeCrafting/rss-in-discord/tree/release/v0.1.0)?

**Comment by firesetter** [comment]
Yeah, I forgot to checkout release before starting on this one so I had a bunch of commit history from the wrong branch in here. Wasn't sure if this was the correct way to solve that or not.

**Comment by Alexander-Prime** [comment]
I'd change the base branch here to `release/v0.1.0` and wait to merge until after the dependency is also merged.

If you run into this again later, you can make a new branch locally from the release branch and `git cherry-pick` the commits that are supposed to be on it before pushing.

**Comment by firesetter** [comment]
Sounds good, we'll just merge this after I fix the other branch tonight.

**Pull request merged**
